// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/wazmeow/wazmeow/blob/main/LICENSE",
        "contact": {
            "name": "WazMeow API Support",
            "url": "https://github.com/wazmeow/wazmeow",
            "email": "support@wazmeow.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Verifica o status de saúde da aplicação e todos os seus serviços dependentes (banco de dados, WhatsApp, etc.).\n\n**Informações retornadas:**\n- Status geral da aplicação (healthy/unhealthy)\n- Versão da aplicação\n- Tempo de atividade (uptime)\n- Status individual de cada serviço\n- Timestamp da verificação\n\n**Status possíveis:**\n- ` + "`" + `healthy` + "`" + `: Todos os serviços funcionando normalmente\n- ` + "`" + `unhealthy` + "`" + `: Um ou mais serviços com problemas\n- ` + "`" + `degraded` + "`" + `: Serviços funcionando com limitações",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health Check da aplicação",
                "responses": {
                    "200": {
                        "description": "Aplicação e serviços saudáveis",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wazmeow_internal_http_dto.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wazmeow_internal_http_dto.HealthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "Um ou mais serviços indisponíveis",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Retorna métricas detalhadas e estatísticas de performance da aplicação, incluindo informações sobre sessões, WhatsApp e sistema.\n\n**Métricas incluídas:**\n\n**Sessões:**\n- Total de sessões criadas\n- Sessões conectadas/desconectadas\n- Sessões com erro\n- Sessões ativas\n\n**WhatsApp:**\n- Total de clientes WhatsApp\n- Clientes conectados e autenticados\n- Mensagens enviadas e recebidas\n- Clientes com erro\n\n**Sistema:**\n- Tempo de atividade (uptime)\n- Uso de memória\n- Uso de CPU\n- Status do banco de dados\n- Conexões ativas do banco",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Métricas da aplicação",
                "responses": {
                    "200": {
                        "description": "Métricas coletadas com sucesso",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wazmeow_internal_http_dto.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wazmeow_internal_http_dto.MetricsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Erro interno ao coletar métricas",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Cria uma nova sessão WhatsApp com configuração opcional de proxy. A sessão é criada no estado 'disconnected' e pode ser conectada posteriormente.\n\n**Exemplos de uso:**\n- Sessão simples: ` + "`" + `{\"name\": \"minha-sessao\"}` + "`" + `\n- Sessão com proxy HTTP: ` + "`" + `{\"name\": \"sessao-proxy\", \"proxy_host\": \"78.24.204.134\", \"proxy_port\": 62122, \"proxy_type\": \"http\", \"username\": \"user\", \"password\": \"pass\"}` + "`" + `\n- Sessão com proxy SOCKS5: ` + "`" + `{\"name\": \"sessao-socks5\", \"proxy_host\": \"78.24.204.134\", \"proxy_port\": 62123, \"proxy_type\": \"socks5\"}` + "`" + `",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Criar nova sessão WhatsApp",
                "parameters": [
                    {
                        "description": "Dados da sessão",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.CreateSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Sessão criada com sucesso",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wazmeow_internal_http_dto.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wazmeow_internal_http_dto.SessionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Dados inválidos (nome muito curto, proxy inválido, etc.)",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Sessão com este nome já existe",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Dados válidos mas incompatíveis (ex: username sem password)",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Lista todas as sessões WhatsApp registradas no sistema com informações detalhadas incluindo status, configuração de proxy e timestamps.\n\n**Filtros disponíveis:**\n- ` + "`" + `status` + "`" + `: Filtra sessões por status (disconnected, connecting, connected)\n\n**Resposta inclui:**\n- Lista de sessões com configuração completa\n- Total de sessões encontradas\n- Informações de proxy (se configurado)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Listar sessões WhatsApp",
                "parameters": [
                    {
                        "enum": [
                            "disconnected",
                            "connecting",
                            "connected"
                        ],
                        "type": "string",
                        "description": "Filtrar por status da sessão",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de sessões recuperada com sucesso",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wazmeow_internal_http_dto.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wazmeow_internal_http_dto.SessionListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Parâmetros de filtro inválidos",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Deleta uma sessão WhatsApp específica por ID ou nome. Sempre força a deleção mesmo se conectada",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Deletar sessão WhatsApp",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da sessão (UUID) ou nome da sessão",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sessão deletada",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wazmeow_internal_http_dto.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wazmeow_internal_http_dto.DeleteSessionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Identificador da sessão inválido",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Sessão não encontrada",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/connect": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Inicia o processo de conexão de uma sessão WhatsApp. Se a sessão não estiver autenticada, gera um QR Code para escaneamento.\n\n**Fluxo de conexão:**\n1. Sessão não autenticada: Retorna QR Code para escaneamento\n2. Sessão autenticada: Conecta diretamente ao WhatsApp\n3. Sessão já conectada: Retorna erro 409\n\n**Identificadores aceitos:**\n- UUID da sessão: ` + "`" + `4ee6195b-6a0f-4c85-a4ee-673ee15f14c8` + "`" + `\n- Nome da sessão: ` + "`" + `minha-sessao` + "`" + `",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Conectar sessão WhatsApp",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"minha-sessao\"",
                        "description": "ID da sessão (UUID) ou nome da sessão",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Processo de conexão iniciado (QR Code gerado ou sessão conectada)",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wazmeow_internal_http_dto.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wazmeow_internal_http_dto.ConnectSessionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Identificador da sessão inválido ou malformado",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Sessão não encontrada com o identificador fornecido",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Sessão já está conectada",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor ou falha na conexão WhatsApp",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna as informações detalhadas de uma sessão específica por ID ou nome, incluindo status completo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Obter detalhes da sessão",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da sessão (UUID) ou nome da sessão",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detalhes da sessão",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wazmeow_internal_http_dto.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wazmeow_internal_http_dto.SessionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Identificador da sessão inválido",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Sessão não encontrada",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Desconecta a sessão do WhatsApp, encerrando a comunicação",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Desconectar sessão (logout)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da sessão (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sessão desconectada",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wazmeow_internal_http_dto.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wazmeow_internal_http_dto.DisconnectSessionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "ID da sessão inválido",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Sessão não encontrada",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Sessão já desconectada",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/pairphone": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Emparelha um telefone com a sessão WhatsApp por ID ou nome",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Emparelhar telefone com sessão",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da sessão (UUID) ou nome da sessão",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados do telefone",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.PairPhoneRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Telefone emparelhado",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wazmeow_internal_http_dto.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wazmeow_internal_http_dto.PairPhoneResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Dados inválidos",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Sessão não encontrada",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/proxy/set": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Configura ou atualiza a configuração de proxy para uma sessão existente. O proxy será usado para todas as conexões WhatsApp desta sessão.\n\n**Tipos de proxy suportados:**\n- HTTP: Proxy HTTP/HTTPS padrão\n- SOCKS5: Proxy SOCKS5 com suporte a autenticação\n\n**Exemplos de configuração:**\n- Proxy HTTP: ` + "`" + `{\"proxy_host\": \"78.24.204.134\", \"proxy_port\": 62122, \"proxy_type\": \"http\"}` + "`" + `\n- Proxy com autenticação: ` + "`" + `{\"proxy_host\": \"78.24.204.134\", \"proxy_port\": 62122, \"proxy_type\": \"http\", \"username\": \"user\", \"password\": \"pass\"}` + "`" + `\n- Proxy SOCKS5: ` + "`" + `{\"proxy_host\": \"78.24.204.134\", \"proxy_port\": 62123, \"proxy_type\": \"socks5\", \"username\": \"user\", \"password\": \"pass\"}` + "`" + `",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Configurar proxy para sessão",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"minha-sessao\"",
                        "description": "ID da sessão (UUID) ou nome da sessão",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Configuração do proxy",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ProxySetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Proxy configurado com sucesso",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wazmeow_internal_http_dto.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wazmeow_internal_http_dto.ProxySetResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Dados de proxy inválidos (host, porta, tipo, etc.)",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Sessão não encontrada",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Configuração de proxy inválida (ex: username sem password)",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/qr": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Gera um QR Code para autenticação de uma sessão WhatsApp específica por ID ou nome",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Gerar QR Code para autenticação",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da sessão (UUID) ou nome da sessão",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "QR Code gerado",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wazmeow_internal_http_dto.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wazmeow_internal_http_dto.QRCodeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Identificador da sessão inválido",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Sessão não encontrada",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Sessão já autenticada",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "wazmeow_internal_http_dto.ConnectSessionResponse": {
            "description": "Resposta da operação de conexão de sessão",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "QR Code gerado. Escaneie com seu WhatsApp."
                },
                "needs_auth": {
                    "type": "boolean",
                    "example": true
                },
                "qr_code": {
                    "type": "string",
                    "example": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."
                },
                "session": {
                    "$ref": "#/definitions/wazmeow_internal_http_dto.SessionResponse"
                }
            }
        },
        "wazmeow_internal_http_dto.CreateSessionRequest": {
            "description": "Dados para criação de uma nova sessão WhatsApp",
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "minha-sessao"
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "YGFEu7Wx"
                },
                "proxy_host": {
                    "type": "string",
                    "example": "78.24.204.134"
                },
                "proxy_port": {
                    "type": "integer",
                    "maximum": 65535,
                    "minimum": 1,
                    "example": 62122
                },
                "proxy_type": {
                    "enum": [
                        "http",
                        "socks5"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ProxyType"
                        }
                    ],
                    "example": "http"
                },
                "username": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "sgQ4BJZs"
                }
            }
        },
        "wazmeow_internal_http_dto.DeleteSessionResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "wazmeow_internal_http_dto.DisconnectSessionResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "session": {
                    "$ref": "#/definitions/wazmeow_internal_http_dto.SessionResponse"
                }
            }
        },
        "wazmeow_internal_http_dto.ErrorResponse": {
            "description": "Resposta de erro padrão da API",
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INTERNAL_ERROR"
                },
                "context": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "details": {
                    "type": "string",
                    "example": "Detalhes técnicos do erro"
                },
                "error": {
                    "type": "string",
                    "example": "Erro interno do servidor"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                },
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                }
            }
        },
        "wazmeow_internal_http_dto.HealthResponse": {
            "description": "Resposta do health check da aplicação",
            "type": "object",
            "properties": {
                "services": {
                    "type": "object",
                    "additionalProperties": true
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "uptime": {
                    "type": "string",
                    "example": "2h30m45s"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "wazmeow_internal_http_dto.MetricsResponse": {
            "description": "Métricas completas da aplicação",
            "type": "object",
            "properties": {
                "sessions": {
                    "$ref": "#/definitions/wazmeow_internal_http_dto.SessionMetrics"
                },
                "system": {
                    "$ref": "#/definitions/wazmeow_internal_http_dto.SystemMetrics"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "whatsapp": {
                    "$ref": "#/definitions/wazmeow_internal_http_dto.WhatsAppMetrics"
                }
            }
        },
        "wazmeow_internal_http_dto.PairPhoneRequest": {
            "description": "Dados para emparelhamento com número de telefone",
            "type": "object",
            "required": [
                "phone_number"
            ],
            "properties": {
                "phone_number": {
                    "type": "string",
                    "example": "5511999999999"
                }
            }
        },
        "wazmeow_internal_http_dto.PairPhoneResponse": {
            "description": "Resposta do emparelhamento com telefone",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Telefone emparelhado com sucesso"
                },
                "phone_number": {
                    "type": "string",
                    "example": "5511999999999"
                },
                "session_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "wazmeow_internal_http_dto.ProxyConfigResponse": {
            "description": "Configuração do proxy",
            "type": "object",
            "properties": {
                "host": {
                    "type": "string",
                    "example": "78.24.204.134"
                },
                "password": {
                    "type": "string",
                    "example": "YGFEu7Wx"
                },
                "port": {
                    "type": "integer",
                    "example": 62122
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ProxyType"
                        }
                    ],
                    "example": "http"
                },
                "username": {
                    "type": "string",
                    "example": "sgQ4BJZs"
                }
            }
        },
        "wazmeow_internal_http_dto.ProxySetRequest": {
            "description": "Configuração de proxy para a sessão",
            "type": "object",
            "required": [
                "proxy_host",
                "proxy_port",
                "proxy_type"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "YGFEu7Wx"
                },
                "proxy_host": {
                    "type": "string",
                    "example": "78.24.204.134"
                },
                "proxy_port": {
                    "type": "integer",
                    "maximum": 65535,
                    "minimum": 1,
                    "example": 62122
                },
                "proxy_type": {
                    "enum": [
                        "http",
                        "socks5"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/wazmeow_internal_http_dto.ProxyType"
                        }
                    ],
                    "example": "http"
                },
                "username": {
                    "type": "string",
                    "example": "sgQ4BJZs"
                }
            }
        },
        "wazmeow_internal_http_dto.ProxySetResponse": {
            "description": "Resposta da configuração de proxy",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Proxy configurado com sucesso"
                },
                "proxy_url": {
                    "type": "string",
                    "example": "http://proxy.example.com:8080"
                },
                "session_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "wazmeow_internal_http_dto.ProxyType": {
            "description": "Tipo de proxy suportado",
            "type": "string",
            "enum": [
                "http",
                "socks5"
            ],
            "x-enum-varnames": [
                "ProxyTypeHTTP",
                "ProxyTypeSOCKS5"
            ]
        },
        "wazmeow_internal_http_dto.QRCodeResponse": {
            "description": "Resposta com QR Code para autenticação",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "QR Code gerado com sucesso"
                },
                "qr_code": {
                    "type": "string",
                    "example": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."
                },
                "session_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "wazmeow_internal_http_dto.SessionListResponse": {
            "description": "Lista de sessões WhatsApp",
            "type": "object",
            "properties": {
                "sessions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/wazmeow_internal_http_dto.SessionResponse"
                    }
                },
                "total": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "wazmeow_internal_http_dto.SessionMetrics": {
            "description": "Métricas relacionadas às sessões WhatsApp",
            "type": "object",
            "properties": {
                "active": {
                    "type": "integer",
                    "example": 4
                },
                "connected": {
                    "type": "integer",
                    "example": 5
                },
                "disconnected": {
                    "type": "integer",
                    "example": 3
                },
                "error": {
                    "type": "integer",
                    "example": 1
                },
                "total": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "wazmeow_internal_http_dto.SessionResponse": {
            "description": "Dados de uma sessão WhatsApp",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "minha-sessao"
                },
                "proxy_config": {
                    "$ref": "#/definitions/wazmeow_internal_http_dto.ProxyConfigResponse"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "disconnected",
                        "connecting",
                        "connected"
                    ],
                    "example": "connected"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T12:30:00Z"
                },
                "wa_jid": {
                    "type": "string",
                    "example": "5511999999999@s.whatsapp.net"
                }
            }
        },
        "wazmeow_internal_http_dto.SuccessResponse": {
            "description": "Resposta de sucesso padrão da API",
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Operação realizada com sucesso"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "wazmeow_internal_http_dto.SystemMetrics": {
            "description": "Métricas relacionadas ao sistema",
            "type": "object",
            "properties": {
                "cpu_usage": {
                    "type": "string",
                    "example": "15%"
                },
                "database_connections": {
                    "type": "integer",
                    "example": 5
                },
                "database_status": {
                    "type": "string",
                    "example": "healthy"
                },
                "memory_usage": {
                    "type": "string",
                    "example": "256MB"
                },
                "uptime": {
                    "type": "string",
                    "example": "2h30m45s"
                }
            }
        },
        "wazmeow_internal_http_dto.WhatsAppMetrics": {
            "description": "Métricas relacionadas ao WhatsApp",
            "type": "object",
            "properties": {
                "authenticated_clients": {
                    "type": "integer",
                    "example": 2
                },
                "connected_clients": {
                    "type": "integer",
                    "example": 3
                },
                "error_clients": {
                    "type": "integer",
                    "example": 1
                },
                "messages_received": {
                    "type": "integer",
                    "example": 75
                },
                "messages_sent": {
                    "type": "integer",
                    "example": 150
                },
                "total_clients": {
                    "type": "integer",
                    "example": 5
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API Key para autenticação. Configure AUTH_ENABLED=true e AUTH_TYPE=api_key no .env. Exemplo: X-API-Key: sua-chave-api-aqui",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        },
        "BasicAuth": {
            "type": "basic"
        }
    },
    "tags": [
        {
            "description": "Operações de gerenciamento de sessões WhatsApp",
            "name": "Sessions"
        },
        {
            "description": "Endpoints de monitoramento e saúde da aplicação",
            "name": "Health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "WazMeow API",
	Description:      "Autenticação básica HTTP (username:password). Configure AUTH_ENABLED=true e AUTH_TYPE=basic no .env. Exemplo: Authorization: Basic dXNlcjpwYXNz",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
